- name: disable apt update on startup
  service: name=apt-daily.service enabled=no

- name: disable apt update timer
  service: name=apt-daily.timer enabled=no

- name: update aptitude cache
  tags: [general]
  apt: update_cache=yes
  register: result
  until: result|succeeded
  retries: 10
  delay: 10

- name: install prerequisite packages
  tags: [general]
  environment:
    DEBIAN_FRONTEND: noninteractive
  apt: pkg={{item}} force=yes
  with_items:
         - acl
         - aptitude
         - curl
         - git
         - nginx
         - maven
         - mysql-server
         - openjdk-8-jdk
         - python-psycopg2
         - python-jinja2
         - python-httplib2
         - python-mysqldb
         - python-requests
         - python-pycurl

- name: upgrade server packages
  tags: [general]
  apt: upgrade=full

- name: create group
  tags: [general]
  group: name="{{username}}"

- name: create user
  tags: [general]
  user: name="{{username}}" password="{{userpass}}" update_password="on_create"
        group="{{username}}" groups=sudo
        shell=/bin/bash

- name: download jetty-runner
  tags: [apps, general]
  become_user: "{{username}}"
  get_url:
          url={{jetty_download_url}}
          dest={{install_dir}}/jetty-runner.jar

- name: config jetty-runner
  tags: [apps, general]
  copy: src=jetty.xml dest={{install_dir}}/jetty.xml

- name: configure nginx (api server)
  tags: [nginx]
  template: src=upload.conf.j2 dest=/etc/nginx/conf.d/upload.conf owner=root group=root mode=0644
  notify:
    - restart nginx

- name: Configure MySQL user
  mysql_user: name={{mysql_user}} host=localhost password={{mysql_pass}} priv={{api_server_database}}.*:ALL/{{auth_server_database}}.*:ALL state=present

- include: ldap.yml
- include: hspc.yml
- include: sample-data.yml
