- name: checkout fhir starter
  tags: [apps]
  become_user: "{{username}}"
  git: repo={{fhir_starter_repo}}
       version={{fhir_starter_branch}}
       dest={{install_dir}}/apps/static
       update={{update_repositories}}

- name: configure sample apps server (services.js)
  tags: [apps]
  become_user: "{{username}}"
  template: src="config/services.js.j2"
            dest="{{install_dir}}/apps/static/fhirStarter/services.js"
            owner="{{username}}" group="{{username}}" mode=0644

- name: configure sample apps server (apps.json)
  tags: [apps]
  become_user: "{{username}}"
  template: src="config/apps.json.j2"
            dest="{{install_dir}}/apps/static/fhirStarter/apps.json"
            owner="{{username}}" group="{{username}}" mode=0644

- name: checkout cardiac risk app
  tags: [apps]
  become_user: "{{username}}"
  git: repo={{cardiac_risk_repo}}
       version={{cardiac_risk_branch}}
       dest={{install_dir}}/apps/static/apps/cardiac-risk
       update={{update_repositories}}
       force=yes

- name: checkout bp centiles app
  tags: [apps]
  become_user: "{{username}}"
  git: repo={{bp_centiles_repo}}
       version={{bp_centiles_branch}}
       dest={{install_dir}}/apps/static/apps/bp-centiles
       update={{update_repositories}}
       force=yes

- name: checkout growth chart app
  tags: [apps]
  become_user: "{{username}}"
  git: repo={{growth_chart_repo}}
       version={{growth_chart_branch}}
       dest={{install_dir}}/apps/static/apps/growth-chart
       update={{update_repositories}}
       force=yes

- name: checkout fhir demo app
  tags: [apps]
  become_user: "{{username}}"
  git: repo={{fhir_demo_app_repo}}
       version={{fhir_demo_app_branch}}
       dest={{install_dir}}/apps/static/apps/fhir-demo
       update={{update_repositories}}
       force=yes

- name: configure sample apps
  tags: [apps]
  become_user: "{{username}}"
  shell: sed -i -e 's/node_modules\/fhirclient\/fhir-client\.js/\.\.\/\.\.\/js\/fhir-client\.js/' {{install_dir}}/apps/static/apps/{{item}}
  with_items:
        - bp-centiles/index.html
        - bp-centiles/launch.html
        - cardiac-risk/index.html
        - cardiac-risk/launch.html
        - growth-chart/index.html
        - growth-chart/launch.html
        - fhir-demo/app/index.html
        - fhir-demo/app/launch.html

- name: generate self-signed ssl certificate (apps server)
  tags: [apps]
  when: app_server_secure_http and not use_custom_ssl_certificates
  shell: creates=/etc/nginx/ssl/apps.crt
         /bin/echo -e "{{app_server_ssl_country}}\n{{app_server_ssl_province}}\n{{app_server_ssl_locality}}\n{{app_server_ssl_organization}}\n{{app_server_ssl_division}}\n{{app_server_host}}\n{{app_server_ssl_email}}\n" | openssl req -x509 -nodes -days 365 -newkey rsa:2048 -keyout /etc/nginx/ssl/apps.key -out /etc/nginx/ssl/apps.crt

- name: configure nginx (sample apps)
  tags: [apps,nginx]
  template: src=nginx_apps.j2 dest=/etc/nginx/sites-enabled/apps owner=root group=root mode=0644
  notify:
    - restart nginx

- name: checkout sample patients
  tags: [patients, load_patients]
  become_user: "{{username}}"
  git: repo={{sample_patients_repo}}
       version={{sample_patients_branch}}
       dest={{install_dir}}/sample-patients
       update={{update_repositories}}
  register: sample_patients_checkout

- name: build sample patients
  tags: [patients, load_patients]
  become_user: "{{username}}"
  shell: chdir={{install_dir}}/sample-patients/bin
         python generate.py --write-fhir ../generated-data {{sample_patients_generator_params}}

- name: wait for api server to become available
  tags: [smart_on_fhir, reset_db, load_patients]
  wait_for: port=9002

- name: list sample patients
  tags: [patients, load_patients]
  shell: ls {{install_dir}}/sample-patients/generated-data/*.xml | head -n {{sample_patients_limit}}
  register: sample_patient_files

- name: load sample patients
  tags: [patients, load_patients]
  shell: "chdir={{install_dir}}/sample-patients/generated-data/
         curl
           'http://localhost:9002/data/?'
           -H 'Content-Type: application/xml+fhir'
           --data-binary @{{item}}"
  with_items: "{{sample_patient_files.stdout_lines}}"

- name: list custom patients (json)
  tags: [patients, load_patients]
  shell: ls {{install_dir}}/sample-patients/custom-data/*.json
  register: custom_patient_files_json

- name: load custom patients (json)
  tags: [patients, load_patients]
  shell: "chdir={{install_dir}}/sample-patients/custom-data/
         curl
           'http://localhost:9002/data/?'
           -H 'Content-Type: application/json+fhir'
           --data-binary @{{item}}"
  with_items: "{{custom_patient_files_json.stdout_lines}}"

- meta: flush_handlers
