---
# *** Main configuration file for the SMART-on-FHIR LDAP Server Installer ***

# When set to true will force TLS and disalow anonymous binds for the LDAP server
ldap_server_tls: false

# Self-signed SSL certificate settings (if generating self-signed certificates)
ldap_server_ssl_country: US
ldap_server_ssl_province: MA
ldap_server_ssl_locality: Boston
ldap_server_ssl_organization: Example Company
ldap_server_ssl_division: support
ldap_server_ssl_email: support@{{ldap_server_domain}}
