---
 - name: configure mysql user
   tags: [api-dstu2-all, api-dstu2-data, smart-platform]
   mysql_user: name={{mysql_user}} host=localhost password={{mysql_pass}} priv={{api_dstu2_mysql_privilage}} state=present

 - name: drop the api-dstu2-server database
   tags: [api-dstu2-all, api-dstu2-data, smart-platform]
   mysql_db: name={{api_dstu2_database}} state=absent

 - name: drop the {{api_dstu2_database}}${{api_dstu2_baseline_snapshot}} snapshot
   tags: [api-dstu2-all, api-dstu2-data, smart-platform]
   mysql_db: name="{{api_dstu2_database}}${{api_dstu2_baseline_snapshot}}" state=absent

 - name: create the {{api_dstu2_database}} database
   tags: [api-dstu2-all, api-dstu2-data, smart-platform]
   mysql_db: name={{api_dstu2_database}} state=present

 - meta: flush_handlers