# Travis CI configuration file for running tests (from github/edx/configuration)
language: python
python:
  - "2.7"
install:
  - "sudo apt-get install -y npm python-demjson"
  - "pip install --allow-all-external PyYAML==3.11"
  - "pip install --allow-all-external demjson"
  - "pip install --allow-all-external ansible==1.8.2"
script:
  - |
    for yml in $(find . -name "*.yml"); do
      python -c "import sys,yaml; yaml.load(open(sys.argv[1]))" $yml >/dev/null
      if [[ $? -ne 0 ]]; then
        echo "ERROR parsing $yml"
        exit 1
      fi
    done
  - |
    for json in $(find . -name "*.json"); do
      jsonlint -v $json
      if [[ $? -ne 0 ]]; then
        echo "ERROR parsing $json"
        exit 1
      fi
    done
  - |
    plays="smart-on-fhir"
    set -e
    cd provisioning
    for play in $plays; do
      ansible-playbook -i localhost, --syntax-check ${play}.yml
    done
