---
 - name: configure auth server service
   tags: [auth-all, auth-server, smart-platform]
   template: src=persona-auth-server.service.j2
             dest=/etc/systemd/system/persona-auth-server.service
             owner=root group=root mode=0644

 - name: enable persona-auth server service
   tags: [auth-all, auth-server, smart-platform]
   shell: systemctl enable persona-auth-server.service

 - name: reload systemd daemon
   tags: [auth-all, auth-server, smart-platform]
   shell: systemctl daemon-reload

 - name: stop persona-auth server
   tags: [auth-all, auth-server, smart-platform]
   service: name=persona-auth-server state=stopped

 - name: restart persona-auth server
   tags: [auth-all, auth-server, smart-platform]
   service: name=persona-auth-server enabled=yes state=restarted

 - name: generate self-signed ssl certificate (persona-auth server)
   tags: [auth-all, auth-server, smart-platform]
   when: persona_auth_server_secure_http and not use_custom_ssl_certificates
   shell: creates=/etc/nginx/ssl/persona-auth.crt
          /bin/echo -e "{{auth_server_ssl_country}}\n{{auth_server_ssl_province}}\n{{auth_server_ssl_locality}}\n{{auth_server_ssl_organization}}\n{{auth_server_ssl_division}}\n{{persona_auth_server_host}}\n{{auth_server_ssl_email}}\n" | openssl req -x509 -nodes -days 365 -newkey rsa:2048 -keyout /etc/nginx/ssl/persona-auth.key -out /etc/nginx/ssl/persona-auth.crt

 - name: import persona-auth server certificate in truststore (persona-auth server)
   tags: [auth-all, auth-server, smart-platform]
   when: persona_auth_server_secure_http
   shell: /bin/echo -e "{{keystore_password}}\nyes\n" | keytool
            -importcert -trustcacerts
            -alias persona-auth
            -file /etc/nginx/ssl/persona-auth.crt
            -keystore {{install_dir}}/keystore

 - name: configure nginx (persona-auth server)
   tags: [auth-all, auth-server, smart-platform]
   template: src=nginx_persona_auth.j2 dest=/etc/nginx/sites-enabled/persona-auth owner=root group=root mode=0644
   notify:
     - restart nginx

 - name: verify persona-auth-server is available
   tags: [auth-all, auth-server, verify, smart-platform]
   wait_for: host={{persona_auth_server_internal_host}} port={{persona_auth_server_internal_port}}

 - meta: flush_handlers
