---
 - name: checkout api-dstu2-sample patients
   tags: [api-dstu2-sample-data, smart-platform]
   become_user: "{{username}}"
   git: repo={{api_dstu2_sample_patients_repo}}
        version={{api_dstu2_sample_patients_branch}}
        dest={{install_dir}}/api-dstu2-sample-patients
        update={{update_repositories}}
   register: api_dstu2_sample_patients_checkout

 - name: build api-dstu2-sample patients
   tags: [api-dstu2-sample-data, smart-platform]
   become_user: "{{username}}"
   shell: chdir={{install_dir}}/api-dstu2-sample-patients/bin
          python generate.py --write-fhir ../generated-data {{api_dstu2_sample_patients_generator_params}}

 - name: configure api-dstu2-server service (open)
   tags: [api-dstu2-sample-data, smart-platform]
   vars:
     fhir_server_security_mode: open
   template: src=api-dstu2-server.service.j2
             dest=/etc/systemd/system/api-dstu2-server.service
             owner=root group=root mode=0644

 - name: enable api-dstu2-server service
   tags: [api-dstu2-sample-data, smart-platform]
   shell: systemctl enable api-dstu2-server.service

 - name: reload systemd daemon
   tags: [api-dstu2-sample-data, smart-platform]
   shell: systemctl daemon-reload

 - name: restart api-dstu2-server
   tags: [api-dstu2-sample-data, smart-platform]
   service: name=api-dstu2-server state=restarted

 - name: wait for api-dstu2-server to become available
   tags: [api-dstu2-sample-data, smart-platform]
   wait_for: port={{api_dstu2_internal_port}}

 - name: list api-dstu2-sample patients
   tags: [api-dstu2-sample-data, smart-platform]
   shell: ls {{install_dir}}/api-dstu2-sample-patients/generated-data/*.xml | head -n {{api_dstu2_sample_patients_limit}}
   register: api_dstu2_sample_patient_files

 - name: load api-dstu2-sample patients
   tags: [api-dstu2-sample-data, smart-platform]
   shell: "chdir={{install_dir}}/api-dstu2-sample-patients/generated-data/
          curl
            'http://localhost:{{api_dstu2_internal_port}}/data/?'
            -H 'Content-Type: application/xml+fhir'
            --data-binary @{{item}}"
   with_items: "{{api_dstu2_sample_patient_files.stdout_lines}}"

 - name: list custom patients (json)
   tags: [api-dstu2-sample-data, smart-platform]
   shell: ls {{install_dir}}/api-dstu2-sample-patients/custom-data/*.json
   register: api_dstu2_custom_patient_files_json

 - name: load custom patients (json)
   tags: [api-dstu2-sample-data, smart-platform]
   shell: "chdir={{install_dir}}/api-dstu2-sample-patients/custom-data/
          curl
            'http://localhost:9002/data/?'
            -H 'Content-Type: application/json+fhir'
            --data-binary @{{item}}"
   with_items: "{{api_dstu2_custom_patient_files_json.stdout_lines}}"

 - name: configure api-dstu2-server service
   tags: [api-dstu2-sample-data, smart-platform]
   template: src=api-dstu2-server.service.j2
             dest=/etc/systemd/system/api-dstu2-server.service
             owner=root group=root mode=0644

 - name: enable api-dstu2-server service
   tags: [api-dstu2-sample-data, smart-platform]
   shell: systemctl enable api-dstu2-server.service

 - name: reload systemd daemon
   tags: [api-dstu2-sample-data, smart-platform]
   shell: systemctl daemon-reload

 - name: restart api-dstu2-server
   tags: [api-dstu2-sample-data, smart-platform]
   service: name=api-dstu2-server state=restarted

 - meta: flush_handlers
