---

# *** Main configuration file for the API-DSTU2 Installer ***
api_dstu2_server_initial_memory: 128M
api_dstu2_server_max_memory: 256M

# HSPC server configuration
# Schema version maps to HAPI schema and FHIR version
#   HSPC Schema version 1 uses HAPI 1.4 and FHIR DSTU2
#   HSPC Schema version 2 uses HAPI 2.0 and FHIR STU3
api_dstu2_schema_version: 1

# Repositories
api_dstu2_repos_base: "https://bitbucket.org/hspconsortium"
# Note, reference-api-mysql is cloned to gain the SQL install files
api_dstu2_repo_api_mysql_project: "reference-api-mysql"
# Note, reference-api-webapp is cloned to perform a jetty build
api_dstu2_repo_api_webapp_project: "reference-api-webapp-multitenant"
api_dstu2_repo_api_branch: "1.0-HAPI-1.4"

api_dstu2_database: "hspc_{{api_dstu2_schema_version}}_{{api_dstu2_server_smart_sandbox}}"
api_dstu2_baseline_snapshot: initial
api_dstu2_mysql_privilage: "{{api_dstu2_database}}.*:ALL/*.*:ALL,GRANT"

# General settings for the sample patients set
api_dstu2_sample_patients_repo: "https://github.com/smart-on-fhir/sample-patients.git"
api_dstu2_sample_patients_branch: "master"

# General settings for the custom-sample-data
api_dstu2_custom_sample_data_repo: "https://github.com/smart-on-fhir/custom-sample-data.git"
api_dstu2_custom_sample_data_branch: "master"

# choose how many sample patients to load in the server or set to 9999 for all of them
api_dstu2_sample_patients_limit: 20
api_dstu2_include_custom_patients: false

# Additional parameters for the sample patient generator
api_dstu2_sample_patients_generator_params: ""

# DSTU2 API Server settings
api_dstu2_server_internal_host: localhost
api_dstu2_server_internal_port: 8070
api_dstu2_server_internal_base_url: "http://{{api_dstu2_server_internal_host}}:{{api_dstu2_server_internal_port}}{{api_dstu2_server_context}}"
api_dstu2_server_internal_smart_sandbox_url: "{{api_dstu2_server_internal_base_url}}{{api_dstu2_server_smart_sandbox}}"
api_dstu2_server_internal_smart_sandbox_fhir_root_url: "{{api_dstu2_server_internal_smart_sandbox_url}}/data"
api_dstu2_server_internal_smart_sandbox_open_fhir_root_url: "{{api_dstu2_server_internal_smart_sandbox_url}}/open"

# PERSONA DSTU2 API Server settings
persona_api_dstu2_server_internal_host: localhost
persona_api_dstu2_server_internal_port: 8071
persona_api_dstu2_server_internal_base_url: "http://{{persona_api_dstu2_server_internal_host}}:{{persona_api_dstu2_server_internal_port}}{{persona_api_dstu2_server_context}}"
persona_api_dstu2_server_internal_smart_sandbox_url: "{{persona_api_dstu2_server_internal_base_url}}{{persona_api_dstu2_server_smart_sandbox}}"
persona_api_dstu2_server_internal_smart_sandbox_fhir_root_url: "{{persona_api_dstu2_server_internal_smart_sandbox_url}}/data"
persona_api_dstu2_server_internal_smart_sandbox_open_fhir_root_url: "{{persona_api_dstu2_server_internal_smart_sandbox_url}}/open"

# Set this to either "open" or "secured" on the primary endpoint /data
api_dstu2_server_security_mode: secured
# Set this to none to remove open access
api_dstu2_server_open_access_endpoint: open


