---
- name: Configure MySQL user
  tags: [pwm-all, pwm-data, smart-platform]
  mysql_user: name={{mysql_user}} host=localhost password={{mysql_pass}} priv={{mysql_privilage}} state=present

- name: Drop the PWM Server database
  tags: [pwm-all, pwm-data, smart-platform]
  mysql_db: name={{pwm_server_database}} state=absent

- name: Create the PWM Server database
  tags: [pwm-all, pwm-data, smart-platform]
  mysql_db: name={{pwm_server_database}} state=present

- meta: flush_handlers
