---
- name: configure apacheds-server service
  tags: [apacheds-all, apacheds-server, smart-platform]
  template: src=apacheds-server.service.j2
            dest=/etc/systemd/system/apacheds-server.service
            owner=root group=root mode=0644

- name: enable apacheds-server service
  tags: [apacheds-all, apacheds-server, smart-platform]
  shell: systemctl enable apacheds-server.service

- name: reload systemd daemon
  tags: [apacheds-all, apacheds-server, smart-platform]
  shell: systemctl daemon-reload

- name: stop apacheds-server
  tags: [apacheds-all, apacheds-server, smart-platform]
  service: name=apacheds-server state=stopped

- meta: flush_handlers

- name: restart apacheds-server
  tags: [apacheds-all, apacheds-server, smart-platform]
  service: name=apacheds-server enabled=yes state=restarted

- name: verify apacheds-server is available
  tags: [apacheds-all, apacheds-server, verify, smart-platform]
  wait_for: host={{apacheds_server_internal_host}} port={{apacheds_server_internal_port}}
