---
 - name: generate self-signed ssl certificate (apps server)
   tags: [apps-all, apps-server, smart-platform]
   when: app_server_secure_http and not use_custom_ssl_certificates
   shell: creates=/etc/nginx/ssl/apps.crt
          /bin/echo -e "{{app_server_ssl_country}}\n{{app_server_ssl_province}}\n{{app_server_ssl_locality}}\n{{app_server_ssl_organization}}\n{{app_server_ssl_division}}\n{{app_server_host}}\n{{app_server_ssl_email}}\n" | openssl req -x509 -nodes -days 365 -newkey rsa:2048 -keyout /etc/nginx/ssl/apps.key -out /etc/nginx/ssl/apps.crt

 - name: configure nginx (sample apps)
   tags: [apps-all, apps-server, smart-platform]
   template: src=nginx_apps.j2 dest=/etc/nginx/sites-enabled/apps owner=root group=root mode=0644
   notify:
     - restart nginx

 - meta: flush_handlers

 - name: verify app-server is available
   tags: [apps-all, apps-server, verify, smart-platform]
   wait_for: host={{app_server_host}} port={{app_server_port}}

