---
 - name: configure api-dstu2-server service
   tags: [api-dstu2-all, api-dstu2-server, smart-platform]
   template: src=api-dstu2-server.service.j2
             dest=/etc/systemd/system/api-dstu2-server.service
             owner=root group=root mode=0644

 - name: enable api-dstu2-server service
   tags: [api-dstu2-all, api-dstu2-server, smart-platform]
   shell: systemctl enable api-dstu2-server.service

 - name: reload systemd daemon
   tags: [api-dstu2-all, api-dstu2-server, smart-platform]
   shell: systemctl daemon-reload

 - name: stop api-dstu2-server
   tags: [api-dstu2-all, api-dstu2-server, smart-platform]
   service: name=api-dstu2-server state=stopped

 - name: generate self-signed ssl certificate (api-dstu2-server)
   tags: [api-dstu2-all, api-dstu2-server, smart-platform]
   when: use_secure_http and not use_custom_ssl_certificates
   shell: creates=/etc/nginx/ssl/api-dstu2.crt
          /bin/echo -e "{{api_dstu2_server_ssl_country}}\n{{api_dstu2_server_ssl_province}}\n{{api_dstu2_server_ssl_locality}}\n{{api_dstu2_server_ssl_organization}}\n{{api_dstu2_server_ssl_division}}\n{{api_dstu2_server_host}}\n{{api_dstu2_server_ssl_email}}\n" | openssl req -x509 -nodes -days 365 -newkey rsa:2048 -keyout /etc/nginx/ssl/api-dstu2.key -out /etc/nginx/ssl/api-dstu2.crt

 - name: import api-dstu2-server certificate in truststore
   tags: [api-dstu2-all, api-dstu2-server, smart-platform]
   when: use_secure_http
   shell: /bin/echo -e "{{keystore_password}}\nyes\n" | keytool
            -importcert -trustcacerts
            -alias api-dstu2
            -file /etc/nginx/ssl/api-dstu2.crt
            -keystore {{install_dir}}/keystore

 - name: configure nginx (api-dstu2-server)
   tags: [api-dstu2-all, api-dstu2-server, smart-platform]
   template: src=nginx_api_dstu2.j2 dest=/etc/nginx/sites-enabled/api_dstu2 owner=root group=root mode=0644
   notify:
     - restart nginx

 - meta: flush_handlers

 - name: restart api-dstu2-server
   tags: [api-dstu2-all, api-dstu2-server, smart-platform]
   service: name=api-dstu2-server enabled=yes state=restarted

 - name: verify api-dstu2-server is available
   tags: [api-dstu2-all, api-dstu2-server, verify, smart-platform]
   wait_for: host={{api_dstu2_server_internal_host}} port={{api_dstu2_server_internal_port}}
