- name: check custom certificate preconditions
  tags: [ldap-all, ldap-server, smart-platform]
  fail: msg="please define the path to the custom certificates that you would like to use"
  when: use_custom_ssl_certificates and (custom_ssl_certificates_path is not defined)

- name: disable apt update on startup
  tags: [ldap-all, ldap-server, smart-platform]
  service: name=apt-daily.service enabled=no

- name: disable apt update timer
  tags: [ldap-all, ldap-server, smart-platform]
  service: name=apt-daily.timer enabled=no

- name: update aptitude cache
  tags: [ldap-all, ldap-server, smart-platform]
  apt: update_cache=yes
  register: result
  until: result|succeeded
  retries: 10
  delay: 10

- name: install prerequisite packages
  tags: [ldap-all, ldap-server, smart-platform]
  environment:
    DEBIAN_FRONTEND: noninteractive
  apt: pkg={{item}} force=yes
  with_items:
         - acl
         - aptitude

- name: create group
  tags: [ldap-all, ldap-server, smart-platform]
  group: name="{{username}}"

- name: create user
  tags: [ldap-all, ldap-server, smart-platform]
  user: name="{{username}}" password="{{userpass}}" update_password="on_create"
        group="{{username}}" groups=sudo
        shell=/bin/bash

- include: ldap-server.yml

- name: verify ldap-server is available
  tags: [verify, ldap-all, ldap-server, smart-platform]
  wait_for: host={{ldap_server_host}} port={{ldap_server_port}}
