- name: check custom certificate preconditions
  tags: [ldap-all, ldap-server, smart-platform]
  fail: msg="please define the path to the custom certificates that you would like to use"
  when: use_custom_ssl_certificates and (custom_ssl_certificates_path is not defined)

- name: disable apt update on startup
  tags: [ldap-all, ldap-server, smart-platform]
  service: name=apt-daily.service enabled=no

- name: disable apt update timer
  tags: [ldap-all, ldap-server, smart-platform]
  service: name=apt-daily.timer enabled=no

- name: update aptitude cache
  tags: [ldap-all, ldap-server, smart-platform]
  apt: update_cache=yes
  register: result
  until: result|succeeded
  retries: 10
  delay: 10

- name: install prerequisite packages
  tags: [ldap-all, ldap-server, smart-platform]
  environment:
    DEBIAN_FRONTEND: noninteractive
  apt: pkg={{item}} force=yes
  with_items:
         - acl
         - aptitude

- name: automatically select the OpenLDAP configuration settings
  tags: [ldap-all, ldap-server, smart-platform]
  shell: /bin/echo "slapd {{item}}" | sudo debconf-set-selections
  with_items:
         - slapd/password1 password {{ldap_server_admin_password}}
         - slapd/password2 password {{ldap_server_admin_password}}
         - slapd/allow_ldap_v2 boolean false
         - shared/organization string {{ldap_server_organization}}
         - slapd/no_configuration boolean false
         - slapd/move_old_database boolean true
         - slapd/purge_database boolean true
         - slapd/domain string {{ldap_server_domain}}
         - slapd/backend boolean HDB

- name: install ldap apt packages
  tags: [ldap-all, ldap-server, smart-platform]
  environment:
    DEBIAN_FRONTEND: noninteractive
  apt: pkg={{item}} force=yes
  with_items:
         - slapd
         - ldap-utils

- name: configure LDAP client tool
  tags: [ldap-all, ldap-server, smart-platform]
  template: src="ldap.conf.j2"
            dest="/etc/ldap/ldap.conf"
            owner=root group=root mode=0644
  register: ldap_checkout

- name: install certificate generator
  tags: [ldap-all, ldap-server, smart-platform]
  when: ldap_server_tls and not use_custom_ssl_certificates
  environment:
    DEBIAN_FRONTEND: noninteractive
  apt: pkg={{item}} force=yes
  with_items:
         - gnutls-bin
         - ssl-cert

- name: create ldap ssl certificates directory
  tags: [ldap-all, ldap-server, smart-platform]
  when: ldap_server_tls
  file: path=/etc/ldap/ssl state=directory owner=root group=ssl-cert mode=0755

- name: configure certificate authority
  tags: [ldap-all, ldap-server, smart-platform]
  when: ldap_server_tls and not use_custom_ssl_certificates
  template: src="ldap_ca.info.j2"
            dest="/etc/ldap/ssl/ldap_ca.info"

- name: generate private key for certificate authority
  tags: [ldap-all, ldap-server, smart-platform]
  when: ldap_server_tls and not use_custom_ssl_certificates
  shell: sh -c "certtool --generate-privkey > /etc/ldap/ssl/ldap_ca_key.pem"

- name: generate self-signed ca certificate
  tags: [ldap-all, ldap-server, smart-platform]
  when: ldap_server_tls and not use_custom_ssl_certificates
  shell: certtool --generate-self-signed
                  --load-privkey /etc/ldap/ssl/ldap_ca_key.pem
                  --template /etc/ldap/ssl/ldap_ca.info
                  --outfile /etc/ldap/ssl/ldap_ca_cert.pem

- name: configure ldap server certificate
  tags: [ldap-all, ldap-server, smart-platform]
  when: ldap_server_tls and not use_custom_ssl_certificates
  template: src="ldap01.info.j2"
            dest="/etc/ldap/ssl/ldap01.info"

- name: generate private key for ldap server
  tags: [ldap-all, ldap-server, smart-platform]
  when: ldap_server_tls and not use_custom_ssl_certificates
  shell: certtool --generate-privkey --bits 1024
                   --outfile /etc/ldap/ssl/ldap01_slapd_key.pem

- name: generate ldap server certificate
  tags: [ldap-all, ldap-server, smart-platform]
  when: ldap_server_tls and not use_custom_ssl_certificates
  shell: certtool --generate-certificate
                  --load-privkey /etc/ldap/ssl/ldap01_slapd_key.pem
                  --load-ca-certificate /etc/ldap/ssl/ldap_ca_cert.pem
                  --load-ca-privkey /etc/ldap/ssl/ldap_ca_key.pem
                  --template /etc/ldap/ssl/ldap01.info
                  --outfile /etc/ldap/ssl/ldap01_slapd_cert.pem

- name: copy custom ldap ssl certificates
  tags: [ldap-all, ldap-server, smart-platform]
  when: ldap_server_tls and use_custom_ssl_certificates
  copy: src={{custom_ssl_certificates_path}}/ldap/
        dest=/etc/ldap/ssl

- name: copy ldap config files
  tags: [ldap-all, ldap-server, smart-platform]
  copy: src={{item}}
        dest=/tmp
  with_items:
    - ldap_disable_auth.ldif
    - ldap_tls_config.ldif

- name: configure ldap server tls
  tags: [ldap-all, ldap-server, smart-platform]
  when: ldap_server_tls
  shell: ldapmodify
           -Y EXTERNAL -H ldapi:///
           -f /tmp/ldap_tls_config.ldif

- name: disable ldap server tls
  tags: [ldap-all, ldap-server, smart-platform]
  when: not ldap_server_tls
  shell: ldapmodify
           -Y EXTERNAL -H ldapi:///
           -f /tmp/ldap_disable_auth.ldif
  failed_when: False

- name: add openldap user to ssl-cert group
  tags: [ldap-all, ldap-server, smart-platform]
  user: name=openldap groups=ssl-cert

- name: set ldap private key permissions
  tags: [ldap-all, ldap-server, smart-platform]
  when: ldap_server_tls
  file: path=/etc/ldap/ssl/ldap01_slapd_key.pem group=ssl-cert mode=640

- name: delete private key for certificate authority
  tags: [ldap-all, ldap-server, smart-platform]
  when: ldap_server_tls
  file: path=/etc/ldap/ssl/ldap_ca_key.pem state=absent

- name: restart ldap server
  tags: [ldap-all, ldap-server, smart-platform]
  service: name=slapd state=restarted

- name: import ldap ca certificate in truststore
  tags: [ldap-all, ldap-server, smart-platform]
  become_user: "{{username}}"
  when: ldap_server_tls
  shell: /bin/echo -e "{{keystore_password}}\nyes\n" | keytool
           -importcert -trustcacerts
           -file /etc/ldap/ssl/ldap_ca_cert.pem
           -keystore {{install_dir}}/keystore
  failed_when: False

- name: import ldap certificate in truststore
  tags: [ldap-all, ldap-server, smart-platform]
  when: ldap_server_tls
  shell: /bin/echo -e "{{keystore_password}}\nyes\n" | keytool
           -importcert -trustcacerts
           -alias ldap
           -file /etc/ldap/ssl/ldap01_slapd_cert.pem
           -keystore {{install_dir}}/keystore

- name: verify ldap-server is available
  tags: [verify, ldap-all, ldap-server, smart-platform]
  wait_for: host={{ldap_server_host}} port={{ldap_server_port}}
