---
 - name: configure auth server service
   tags: [auth-all, auth-server, smart-platform]
   template: src=auth-server.service.j2
             dest=/etc/systemd/system/auth-server.service
             owner=root group=root mode=0644

 - name: enable auth server service
   tags: [auth-all, auth-server, smart-platform]
   shell: systemctl enable auth-server.service

 - name: reload systemd daemon
   tags: [auth-all, auth-server, smart-platform]
   shell: systemctl daemon-reload

 - name: stop auth server
   tags: [auth-all, auth-server, smart-platform]
   service: name=auth-server state=stopped

 - name: restart auth server
   tags: [auth-all, auth-server, smart-platform]
   service: name=auth-server enabled=yes state=restarted

 - name: generate self-signed ssl certificate (auth server)
   tags: [auth-all, auth-server, smart-platform]
   when: use_secure_http and not use_custom_ssl_certificates
   shell: creates=/etc/nginx/ssl/auth.crt
          /bin/echo -e "{{auth_server_ssl_country}}\n{{auth_server_ssl_province}}\n{{auth_server_ssl_locality}}\n{{auth_server_ssl_organization}}\n{{auth_server_ssl_division}}\n{{auth_server_host}}\n{{auth_server_ssl_email}}\n" | openssl req -x509 -nodes -days 365 -newkey rsa:2048 -keyout /etc/nginx/ssl/auth.key -out /etc/nginx/ssl/auth.crt

 - name: import auth server certificate in truststore (auth server)
   tags: [auth-all, auth-server, smart-platform]
   when: use_secure_http
   shell: /bin/echo -e "{{keystore_password}}\nyes\n" | keytool
            -importcert -trustcacerts
            -alias auth
            -file /etc/nginx/ssl/auth.crt
            -keystore {{install_dir}}/keystore

 - name: configure nginx (auth server)
   tags: [auth-all, auth-server, smart-platform]
   template: src=nginx_auth.j2 dest=/etc/nginx/sites-enabled/auth owner=root group=root mode=0644
   notify:
     - restart nginx

 - meta: flush_handlers

 - name: verify auth-server is available
   tags: [auth-all, auth-server, verify, smart-platform]
   wait_for: host={{auth_server_internal_host}} port={{auth_server_internal_port}}
