---
 - name: configure auth server service
   tags: [auth-all, auth-server, smart-platform]
   template: src=auth-server.service.j2
             dest=/etc/systemd/system/auth-server.service
             owner=root group=root mode=0644

 - name: enable auth server service
   tags: [auth-all, auth-server, smart-platform]
   shell: systemctl enable auth-server.service

 - name: reload systemd daemon
   tags: [auth-all, auth-server, smart-platform]
   shell: systemctl daemon-reload

 - name: stop auth server
   tags: [auth-all, auth-server, smart-platform]
   service: name=auth-server state=stopped

 - name: restart auth server
   tags: [auth-all, auth-server, smart-platform]
   service: name=auth-server enabled=yes state=restarted

 - name: configure nginx (auth server)
   tags: [auth-all, auth-server, smart-platform]
   template: src=nginx_auth.j2 dest=/etc/nginx/sites-enabled/auth owner=root group=root mode=0644
   notify:
     - restart nginx

 - meta: flush_handlers

 - name: verify auth-server is available
   tags: [auth-all, auth-server, verify, smart-platform]
   wait_for: host={{auth_server_internal_host}} port={{auth_server_internal_port}}
