---
- name: configure auth server service
  tags: [auth-all, auth-server, smart-platform]
  template: src=persona-auth-server.service.j2
            dest=/etc/systemd/system/persona-auth-server.service
            owner=root group=root mode=0644

- name: enable persona-auth server service
  tags: [auth-all, auth-server, smart-platform]
  shell: systemctl enable persona-auth-server.service

- name: reload systemd daemon
  tags: [auth-all, auth-server, smart-platform]
  shell: systemctl daemon-reload

- name: stop persona-auth server
  tags: [auth-all, auth-server, smart-platform]
  service: name=persona-auth-server state=stopped

- name: restart persona-auth server
  tags: [auth-all, auth-server, smart-platform]
  service: name=persona-auth-server enabled=yes state=restarted

- name: configure nginx (persona-auth server)
  tags: [auth-all, auth-server, smart-platform]
  template: src=nginx_persona_auth.j2 dest=/etc/nginx/sites-enabled/persona-auth owner=root group=root mode=0644
  notify:
    - restart nginx

- meta: flush_handlers

- name: verify persona-auth-server is available
  tags: [auth-all, auth-server, verify, smart-platform]
  wait_for: host={{persona_auth_server_internal_host}} port={{persona_auth_server_internal_port}}
