---
 - name: baseline snapshot
   uri:
     url: "http://localhost:9002/sandbox/snapshot/{{ snapshot_name }}"
     method: POST
     body: '{"action": "{{ snapshot_action }}"}'
     body_format: json
     HEADER_Content-Type: "application/json"
