---
sandbox_manager_server_initial_memory: 128M
sandbox_manager_server_max_memory: 256M

# Version control information
sandbox_manager_project: "sandbox-manager"
sandbox_manager_branch: "master"

# Database schema
sandbox_manager_database: sandman

# Self-signed SSL certificates settings (if generating self-signed certificates)
sandbox_manager_server_ssl_country: "{{default_ssl_country}}"
sandbox_manager_server_ssl_province: "{{default_ssl_province}}"
sandbox_manager_server_ssl_locality: "{{default_ssl_locality}}"
sandbox_manager_server_ssl_organization: "{{default_ssl_organization}}"
sandbox_manager_server_ssl_division: "{{default_ssl_division}}"
sandbox_manager_server_ssl_email: "{{default_ssl_email}}"

# Options
sandbox_manager_server_defaultSystemRoles: USER
sandbox_manager_server_defaultSandboxVisibility: PUBLIC

# Branding
sandbox_manager_company_logo_path: static/branding/smart/images/smart-logo.png
sandbox_manager_company_logo2x_path: static/branding/smart/images/smart-logo@2x.png