---
 - name: checkout fhir starter
   tags: [apps-all, apps-code, smart-platform]
   become_user: "{{username}}"
   git: repo={{fhir_starter_repo}}
        version={{fhir_starter_branch}}
        dest={{install_dir}}/apps/static
        update={{update_repositories}}

 - name: configure sample apps server (services.js)
   tags: [apps-all, apps-code, smart-platform]
   become_user: "{{username}}"
   template: src="config/services.js.j2"
             dest="{{install_dir}}/apps/static/fhirStarter/services.js"
             owner="{{username}}" group="{{username}}" mode=0644

 - name: configure sample apps server (apps.json)
   tags: [apps-all, apps-code, smart-platform]
   become_user: "{{username}}"
   template: src="config/apps.json.j2"
             dest="{{install_dir}}/apps/static/fhirStarter/apps.json"
             owner="{{username}}" group="{{username}}" mode=0644

 - name: checkout cardiac risk app
   tags: [apps-all, apps-code, smart-platform]
   become_user: "{{username}}"
   git: repo={{cardiac_risk_repo}}
        version={{cardiac_risk_branch}}
        dest={{install_dir}}/apps/static/apps/cardiac-risk
        update={{update_repositories}}
        force=yes

 - name: checkout bp centiles app
   tags: [apps-all, apps-code, smart-platform]
   become_user: "{{username}}"
   git: repo={{bp_centiles_repo}}
        version={{bp_centiles_branch}}
        dest={{install_dir}}/apps/static/apps/bp-centiles
        update={{update_repositories}}
        force=yes

 - name: checkout growth chart app
   tags: [apps-all, apps-code, smart-platform]
   become_user: "{{username}}"
   git: repo={{growth_chart_repo}}
        version={{growth_chart_branch}}
        dest={{install_dir}}/apps/static/apps/growth-chart
        update={{update_repositories}}
        force=yes

 - name: checkout fhir demo app
   tags: [apps-all, apps-code, smart-platform]
   become_user: "{{username}}"
   git: repo={{fhir_demo_app_repo}}
        version={{fhir_demo_app_branch}}
        dest={{install_dir}}/apps/static/apps/fhir-demo
        update={{update_repositories}}
        force=yes

 - name: checkout patient picker app
   tags: [apps-all, apps-code, smart-platform]
   become_user: "{{username}}"
   git: repo={{patient_picker_app_repo}}
        version={{patient_picker_app_branch}}
        dest={{install_dir}}/apps/static/apps/patient-picker
        update={{update_repositories}}
        force=yes

 - name: copy patient picker app
   tags: [apps-all, apps-code, smart-platform]
   become_user: "{{username}}"
   shell: |
     mv {{install_dir}}/apps/static/apps/patient-picker/src/main/webapp/static {{install_dir}}/apps/static/apps/patient-picker
     mv {{install_dir}}/apps/static/apps/patient-picker/src/main/webapp/index.html {{install_dir}}/apps/static/apps/patient-picker
     rm -rf {{install_dir}}/apps/static/apps/patient-picker/src/main/webapp

 - name: configure sample apps
   tags: [apps-all, apps-code, smart-platform]
   become_user: "{{username}}"
   shell: sed -i -e 's/node_modules\/fhirclient\/fhir-client\.js/\.\.\/\.\.\/js\/fhir-client\.js/' {{install_dir}}/apps/static/apps/{{item}}
   with_items:
         - bp-centiles/index.html
         - bp-centiles/launch.html
         - cardiac-risk/index.html
         - cardiac-risk/launch.html
         - growth-chart/index.html
         - growth-chart/launch.html
         - fhir-demo/app/index.html
         - fhir-demo/app/launch.html
