---
- name: generate sandbox admin update script
  tags: [apacheds-all, apacheds-sandbox, smart-platform]
  become_user: "{{username}}"
  template: src="update-sandbox-admin-password.ldif.j2"
            dest="{{apacheds_home}}/update-sandbox-admin-password.ldif"

- name: update sandbox admin
  tags: [apacheds-all, apacheds-sandbox, smart-platform]
  become_user: "{{username}}"
  shell: chdir={{apacheds_home}}
         ldapadd
           -x -D {{apacheds_server_system_admin_dn}}
           -w {{apacheds_server_system_admin_initial_password}}
           -f update-sandbox-admin-password.ldif
  failed_when: False

- name: generate sandbox demo update script
  tags: [apacheds-all, apacheds-sandbox, smart-platform]
  become_user: "{{username}}"
  template: src="update-sandbox-demo-password.ldif.j2"
            dest="{{apacheds_home}}/update-sandbox-demo-password.ldif"

- name: update sandbox demo
  tags: [apacheds-all, apacheds-sandbox, smart-platform]
  become_user: "{{username}}"
  shell: chdir={{apacheds_home}}
         ldapadd
           -x -D {{apacheds_server_system_admin_dn}}
           -w {{apacheds_server_system_admin_initial_password}}
           -f update-sandbox-demo-password.ldif
  failed_when: False

