---
 - name: download sandbox manager
   tags: [sandboxmgr, general]
   maven_artifact:
     group_id: org.hspconsortium.sandbox
     artifact_id: hspc-sandbox-manager
     version: 1.0-SNAPSHOT
     packaging: war
     dest: "{{install_dir}}/hspc/sandbox-manager/target"

 - name: build hspc server API server
   tags: [sandboxmgr, general]
   become_user: "{{username}}"
   shell: chdir={{install_dir}}/hspc
        mvn clean install -e -f reference-api-webapp/pom.xml -Pjetty

mvn org.apache.maven.plugins:maven-dependency-plugin:2.8:copy -Dartifact=groupId:artifactId:version[:packaging][:classifier] -DoutputDirectory=[target] -Dmdep.useBaseVersion=true

# todo see about embedding this inside the WAR so it can be self-contained
# then only override if necessary
 - name: config jetty-runner
   tags: [sandboxmgr, general]
   copy: src=jetty.xml dest={{install_dir}}/hspc/sandbox-manager/target/jetty.xml

 - meta: flush_handlers