---
 - name: configure pwm server service
   tags: [pwm-all, pwm-server, smart-platform]
   template: src=pwm-server.service.j2
             dest=/etc/systemd/system/pwm-server.service
             owner=root group=root mode=0644

 - name: enable pwm server service
   tags: [pwm-all, pwm-server, smart-platform]
   shell: systemctl enable pwm-server.service

 - name: reload systemd daemon
   tags: [pwm-all, pwm-server, smart-platform]
   shell: systemctl daemon-reload

 - name: stop pwm server
   tags: [pwm-all, pwm-server, smart-platform]
   service: name=pwm-server state=stopped

 - name: restart pwm server
   tags: [pwm-all, pwm-server, smart-platform]
   service: name=pwm-server enabled=yes state=restarted

 - name: generate self-signed ssl certificate (pwm server)
   tags: [pwm-all, pwm-server, smart-platform]
   when: pwm_server_secure_http and not use_custom_ssl_certificates
   shell: creates=/etc/nginx/ssl/pwm.crt
          /bin/echo -e "{{pwm_server_ssl_country}}\n{{pwm_server_ssl_province}}\n{{pwm_server_ssl_locality}}\n{{pwm_server_ssl_organization}}\n{{pwm_server_ssl_division}}\n{{pwm_server_host}}\n{{pwm_server_ssl_email}}\n" | openssl req -x509 -nodes -days 365 -newkey rsa:2048 -keyout /etc/nginx/ssl/pwm.key -out /etc/nginx/ssl/pwm.crt

 - name: import pwm server certificate in truststore (pwm server)
   tags: [pwm-all, pwm-server, smart-platform]
   when: pwm_server_secure_http
   shell: /bin/echo -e "{{keystore_password}}\nyes\n" | keytool
            -importcert -trustcacerts
            -alias pwm
            -file /etc/nginx/ssl/pwm.crt
            -keystore {{install_dir}}/keystore

 - name: configure nginx (pwm server)
   tags: [pwm-all, pwm-server, smart-platform]
   template: src=nginx_pwm.j2 dest=/etc/nginx/sites-enabled/pwm owner=root group=root mode=0644
   notify:
     - restart nginx

 - meta: flush_handlers

 - name: verify pwm-server is available
   tags: [pwm-all, pwm-server, verify, smart-platform]
   wait_for: host={{pwm_server_internal_host}} port={{pwm_server_internal_port}}
