---
# *** Main configuration file for the ApacheDS Installer ***
apacheds_server_initial_memory: 128M
apacheds_server_max_memory: 256M

# Repositories
apacheds_version: "apacheds-2.0.0-M23"
apacheds_artifact_name: "{{apacheds_version}}.tar.gz"
apacheds_home: "{{install_dir}}/{{apacheds_version}}"
apacheds_artifact_url: "http://mirrors.sonic.net/apache//directory/apacheds/dist/2.0.0-M23/{{apacheds_artifact_name}}"

# Host
apacheds_server_internal_host: "{{apacheds_server_host}}"
apacheds_server_internal_port: "{{apacheds_server_port}}"

# Users
apacheds_server_admin: "admin"
apacheds_server_adminuserdn: "uid={{apacheds_server_admin}},ou=system"
# note, this does not change the password in the apache_ds system
# the apacheds admin password is already set in the apacheds-2.0.0-M23-configured.tar
# if you would like a different password, change it in ApacheDS after deploy
# then change it here for other services to use
apacheds_server_admin_password: "secret"
apacheds_server_test: "test"
apacheds_server_users_ou: "ou=users"
apacheds_server_user_context: "{{apacheds_server_users_ou}},{{apacheds_server_base}}"
apacheds_server_testuserdn: "cn={{apacheds_server_test}},{{apacheds_server_user_context}}"
