- name: checkout mpr monitor app
  tags: [apps-all]
  become_user: "{{username}}"
  git: repo={{mpr_monitor_repo}}
       version={{mpr_monitor_branch}}
       dest={{install_dir}}/apps/rest/mpr_monitor
       update={{update_repositories}}
       force=yes
       depth=1

- name: configure mpr monitor (step 1)
  tags: [apps-all]
  become_user: "{{username}}"
  replace: dest={{install_dir}}/apps/rest/mpr_monitor/settings.py
           regexp='my_web_app'
           replace="{{mpr_monitor_client_id}}"

- name: configure mpr monitor (step 2)
  tags: [apps-all]
  become_user: "{{username}}"
  replace: dest={{install_dir}}/apps/rest/mpr_monitor/settings.py
           regexp='http:\/\/localhost:8000'
           replace="{{mpr_monitor_base}}"

- name: install pip prerequisites to mpr monitor
  tags: [apps-all]
  pip: requirements={{install_dir}}/apps/rest/mpr_monitor/requirements.txt

- name: configure apache (remove default server)
  tags: [apps-all]
  file: path=/etc/apache2/sites-enabled/000-default.conf state=absent

- name: configure apache (mpr monitor server)
  tags: [apps-all]
  template: src=mpr-monitor.conf.j2 dest=/etc/apache2/sites-enabled/mpr-monitor.conf owner=root group=root mode=0644

- name: configure nginx (mpr monitor server)
  tags: [apps-all]
  template: src=nginx_mprmonitor.j2 dest=/etc/nginx/sites-enabled/mprmonitor owner=root group=root mode=0644

- name: restart apache2
  service: name=apache2 state=restarted

- name: checkout disease monograph app
  tags: [apps-all]
  become_user: "{{username}}"
  git: repo={{disease_monograph_repo}}
       version={{disease_monograph_branch}}
       dest={{install_dir}}/demo-apps/disease-monograph
       update={{update_repositories}}
       force=yes
       depth=1

- name: checkout diabetes monograph app
  tags: [apps-all]
  become_user: "{{username}}"
  git: repo={{diabetes_monograph_repo}}
       version={{diabetes_monograph_branch}}
       dest={{install_dir}}/demo-apps/diabetes-monograph
       update={{update_repositories}}
       force=yes
       depth=1

- name: checkout cardiac risk app
  tags: [apps-all]
  become_user: "{{username}}"
  git: repo={{cardiac_risk_repo}}
       version={{cardiac_risk_branch}}
       dest={{install_dir}}/demo-apps/cardiac-risk
       update={{update_repositories}}
       force=yes
       depth=1

- name: checkout bp centiles app
  tags: [apps-all]
  become_user: "{{username}}"
  git: repo={{bp_centiles_repo}}
       version={{bp_centiles_branch}}
       dest={{install_dir}}/demo-apps/bp-centiles
       update={{update_repositories}}
       force=yes
       depth=1

- name: checkout growth chart app
  tags: [apps-all]
  become_user: "{{username}}"
  git: repo={{growth_chart_repo}}
       version={{growth_chart_branch}}
       dest={{install_dir}}/demo-apps/growth-chart
       update={{update_repositories}}
       force=yes
       depth=1

- name: configure demo apps
  tags: [apps-all]
  become_user: "{{username}}"
  replace: dest={{install_dir}}/demo-apps/{{item}}
           regexp='node_modules\/fhirclient\/fhir-client\.js'
           replace="../js/fhir-client.js"
  with_items:
        - bp-centiles/index.html
        - bp-centiles/launch.html
        - cardiac-risk/index.html
        - cardiac-risk/launch.html
        - growth-chart/index.html
        - growth-chart/launch.html
        - diabetes-monograph/index.html
        - diabetes-monograph/launch.html
        - disease-monograph/index.html
        - disease-monograph/launch.html

- name: configure BP Centiles client ID
  tags: [apps-all]
  become_user: "{{username}}"
  replace: dest={{install_dir}}/demo-apps/bp-centiles/launch.html
           regexp='bp_centiles'
           replace="{{bp_centiles_client_id}}"

- name: configure Cardiac Risk client ID
  tags: [apps-all]
  become_user: "{{username}}"
  replace: dest={{install_dir}}/demo-apps/cardiac-risk/launch.html
           regexp='cardiac_risk'
           replace="{{cardiac_risk_client_id}}"

- name: configure Growth Chart client ID
  tags: [apps-all]
  become_user: "{{username}}"
  replace: dest={{install_dir}}/demo-apps/growth-chart/launch.html
           regexp='growth_chart'
           replace="{{growth_chart_client_id}}"

- name: configure Diabetes Monograph client ID
  tags: [apps-all]
  become_user: "{{username}}"
  replace: dest={{install_dir}}/demo-apps/diabetes-monograph/launch.html
           regexp='diabetes_monograph'
           replace="{{diabetes_monograph_client_id}}"

- name: configure Disease Monograph client ID
  tags: [apps-all]
  become_user: "{{username}}"
  replace: dest={{install_dir}}/demo-apps/disease-monograph/launch.html
           regexp='disease_monograph'
           replace="{{disease_monograph_client_id}}"

- name: create js directory
  tags: [apps-all]
  become_user: "{{username}}"
  file: path={{install_dir}}/demo-apps/js state=directory

- name: copy JS client from FHIR Starter
  tags: [apps-all]
  become_user: "{{username}}"
  shell: chdir={{install_dir}}/demo-apps
         cp {{install_dir}}/apps/static/js/fhir-client.js js/.

- name: configure nginx (demo apps)
  tags: [apps-all,nginx]
  template: src=nginx_demo_apps.j2 dest=/etc/nginx/sites-enabled/demo-apps owner=root group=root mode=0644

- name: restart nginx
  service: name=nginx state=restarted
