---
fhir_server_secure_http: false
fhir_server_host: localhost
fhir_server_port: 9080
fhir_server_name: SMART-on-FHIR HSPC Sandbox
app_server_secure_http: false
app_server_host: localhost
app_server_port: 9090
auth_server_secure_http: false
auth_server_host: localhost
auth_server_port: 9085
auth_server_password: secret
sample_patients_branch: hapi-patients-testing
fhir_starter_branch: v0.1.2
cardiac_risk_branch: v0.1.0
bp_centiles_branch: v0.1.1
growth_chart_branch: v0.1.1
fhir_demo_app_branch: v0.1.0
mpr_monitor_branch: v0.1.0
diabetes_monograph_branch: v0.1.0
disease_monograph_branch: v0.1.0
