---
- include: playbook-rebuild-linux.yml

- include: playbook-rebuild-app-code.yml

- include: playbook-rebuild-services.yml

- include: playbook-rebuild-databases.yml

- include: playbook-initialize.yml
