---
- hosts: all:!REMOTEHOST
  become: yes
  vars_files:
    - global_settings.yml
    - custom_settings.yml
  roles:
    - common
    - ldap
    - api-dstu2
    - sandbox-manager
    - apps
    - auth
    - messaging
#    - pwm

- hosts: REMOTEHOST
  remote_user: REMOTEUSER
  gather_facts: no
  pre_tasks:
    - raw: sudo apt-get -y install python-simplejson
  become: yes
  vars_files:
    - custom_settings.yml
  vars:
    api_dstu2_server_host: REMOTEHOST
    app_server_host: REMOTEHOST
    auth_server_host: REMOTEHOST
  roles:
    - common
    - ldap
    - api-dstu2
    - sandbox-manager
    - apps
    - auth
    - messaging
#    - pwm
