---
- name: check custom certificate preconditions
  tags: [apacheds-all, apacheds-server, smart-platform]
  fail: msg="please define the path to the custom certificates that you would like to use"
  when: use_custom_ssl_certificates and (custom_ssl_certificates_path is not defined)

- name: remove existing apacheds installation
  tags: [apacheds-all, apacheds-server, smart-platform]
  file: path="{{apacheds_home}}" state=absent

# for raw apacheds
#- name: download apacheds
#  tags: [apacheds-all, apacheds-server, smart-platform]
#  become_user: "{{username}}"
#  get_url: url={{apacheds_artifact_url}} dest={{install_dir}}
#
#- name: extract apacheds
#  tags: [apacheds-all, apacheds-server, smart-platform]
#  become_user: "{{username}}"
#  unarchive: src="{{install_dir}}/{{apacheds_artifact_name}}" dest="{{install_dir}}" copy=no
#
#- name: setenv.sh properties
#  tags: [apacheds-all, apacheds-server, smart-platform]
#  template: src=setenv.sh.j2 dest="{{apacheds_home}}/bin/setenv.sh" owner="{{username}}" group="{{username}}" mode=0744
#
- name: extract configured apacheds
  tags: [apacheds-all, apacheds-server, smart-platform]
  become_user: "{{username}}"
  unarchive: src="apacheds-2.0.0-M23-configured.tar" dest="{{install_dir}}"

