---
username: fhir
userpass: secretpass
install_dir: "/home/{{username}}"
update_repositories: yes
http_redirect: false
docker_build_repo: "https://github.com/nschwertner/fhir-server-docker-experiment"
fhir_starter_repo: "https://github.com/smart-on-fhir/fhir-starter.git"
cardiac_risk_repo: "https://github.com/smart-on-fhir/cardiac-risk-app.git"
bp_centiles_repo: "https://github.com/smart-on-fhir/bp-centiles-app.git"
growth_chart_repo: "https://github.com/smart-on-fhir/growth-chart-app.git"
fhir_demo_app_repo: "https://github.com/smart-on-fhir/fhir-demo-app.git"
fhir_starter_branch: "master"
cardiac_risk_branch: "master"
bp_centiles_branch: "master"
growth_chart_branch: "master"
fhir_demo_app_branch: "master"
fhir_server_secure_http: false
fhir_server_host: "localhost"
fhir_server_port: 9080
fhir_server_name: "Local FHIR dev server"
app_server_secure_http: false
app_server_host: "localhost"
app_server_port: 9090
auth_server_secure_http: false
auth_server_host: "localhost"
auth_server_port: 9085
auth_server_client: client
auth_server_password: secret

# General settings for the sample patients set
sample_patients_repo: "https://github.com/smart-on-fhir/sample-patients.git"
sample_patients_branch: "master"

# choose how many sample patients to load in the server or set to 9999 for all of them
sample_patients_limit: 10
include_custom_patients: false

# These are convenience variables with the generated base paths of the servers. You
# most likely will never have to touch these.
auth_server_base: "{{
    'https' if auth_server_secure_http else 'http' }}://{{auth_server_host}}{{(
    ':'+auth_server_port|string) if auth_server_port|int not in (80,443) else ''}}"

app_server_base: "{{
        'https' if app_server_secure_http else 'http'}}://{{app_server_host}}{{
        (':'+app_server_port|string) if app_server_port|int not in (80,443) else ''}}"

fhir_server_base: "{{
        'https' if fhir_server_secure_http else 'http'}}://{{fhir_server_host}}{{
        (':'+fhir_server_port|string) if fhir_server_port|int not in (80,443) else ''}}"

# Additional parameters for the sample patient generator
sample_patients_generator_params: ""

mysql_root_pass: password
api_server_database: hapi_pu
auth_server_database: oic
jetty_download_url: "http://central.maven.org/maven2/org/eclipse/jetty/jetty-runner/9.3.6.v20151106/jetty-runner-9.3.6.v20151106.jar"

ldap_server_domain: "example.com"
ldap_server_host: "localhost"
ldap_server_base: "dc=example,dc=com"
ldap_server_uri: "ldap://{{ldap_server_host}}:389"
ldap_server_organization: "Example Company"
ldap_server_admin_password: "password"
ldap_server_tls: false
