---
 - name: checkout repository messaging_project
   tags: [messaging-all, messaging-code, smart-platform]
   become_user: "{{username}}"
   git: repo="{{hspc_repos_base}}/{{messaging_project}}"
        version="{{messaging_branch}}"
        dest="{{install_dir}}/hspc/{{messaging_project}}"
        update={{update_repositories}}

 - name: configure messaging server service
   tags: [messaging-all, messaging-server, smart-platform]
   template: src=messaging-server.service.j2
             dest=/etc/systemd/system/messaging-server.service
             owner=root group=root mode=0644

 - name: enable messaging server service
   tags: [messaging-all, messaging-server, smart-platform]
   shell: systemctl enable messaging-server.service

 - name: reload systemd daemon
   tags: [messaging-all, messaging-server, smart-platform]
   shell: systemctl daemon-reload

 - name: stop messaging server
   tags: [messaging-all, messaging-server, smart-platform]
   service: name=messaging-server state=stopped

 - name: build hspc messaging server
   tags: [messaging-all, messaging-code, smart-platform]
   become_user: "{{username}}"
   shell: chdir={{install_dir}}/hspc
        mvn clean install -e -f reference-messaging/pom.xml

 - name: restart messaging server
   tags: [messaging-all, messaging-server, smart-platform]
   service: name=messaging-server enabled=yes state=restarted

 - name: generate self-signed ssl certificate (messaging server)
   tags: [messaging-all, messaging-server, smart-platform]
   when: messaging_server_secure_http and not use_custom_ssl_certificates
   shell: creates=/etc/nginx/ssl/messaging.crt
          /bin/echo -e "{{messaging_server_ssl_country}}\n{{messaging_server_ssl_province}}\n{{messaging_server_ssl_locality}}\n{{messaging_server_ssl_organization}}\n{{messaging_server_ssl_division}}\n{{messaging_server_host}}\n{{messaging_server_ssl_email}}\n" | openssl req -x509 -nodes -days 365 -newkey rsa:2048 -keyout /etc/nginx/ssl/messaging.key -out /etc/nginx/ssl/messaging.crt

 - name: import messaging server certificate in truststore (messaging server)
   tags: [messaging-all, messaging-server, smart-platform]
   when: messaging_server_secure_http
   shell: /bin/echo -e "{{keystore_password}}\nyes\n" | keytool
            -importcert -trustcacerts
            -alias messaging
            -file /etc/nginx/ssl/messaging.crt
            -keystore {{install_dir}}/keystore

 - name: configure nginx (messaging server)
   tags: [messaging-all, messaging-server, smart-platform]
   template: src=nginx_messaging.j2 dest=/etc/nginx/sites-enabled/messaging owner=root group=root mode=0644
   notify:
     - restart nginx

 - name: verify messaging-server is available
   tags: [messaging-all, messaging-server, verify, smart-platform]
   wait_for: host={{messaging_server_internal_host}} port={{messaging_server_internal_port}}
