---
pwm_server_initial_memory: 128M
pwm_server_max_memory: 256M

# Version control information
pwm_branch: "master"
pwm_project: "pwm"

# Database schema
pwm_server_database: pwm

# Tomcat settings
tomcat_version: 8.5.9
tomcat_artifact_name: "apache-tomcat-{{tomcat_version}}"
tomcat_home: "{{install_dir}}/{{tomcat_artifact_name}}"
tomcat_artifact_url: "http://supergsego.com/apache/tomcat/tomcat-8/v{{tomcat_version}}/bin/{{tomcat_artifact_name}}.tar.gz"
tomcat_shutdown_port: 8005
tomcat_redirect_port: 8443
tomcat_ajp_port: 8009
tomcat_server_name: Catalina
tomcat_default_host: localhost